### ISSUE TITLE
Empty Legend of Nifelheim project appears in the main Kit Visual Studio solution

### ISSUE THREAD

**Issue by vincegogh** [haikarainen/kit#11]
It's empty, but it still looks a little weird having it there. Also, there is another empty project named 'TestArea', not sure if that needs to be removed or not.

As seen here: https://github.com/haikarainen/kit/blob/master/vs2015/Kit/Kit.sln#L17

**Comment by haikarainen** [comment]
Hmm that's weird indeed. Both the TestArea and the Legend of Nifelheim projects should be deleted. I don't have a windows box atm. but let me try to fix that by editing the file instead.

**Comment by haikarainen** [comment]
Please verify
