### ISSUE TITLE
Fails to build with chaiscript-5.8.1/latest

### ISSUE THREAD

**Issue by Ristovski** [haikarainen/kit#12]
Kit fails to compile under chaiscript 5.8.1 (which would be the latest). Upon downgrading to 5.7.0 (which is what Arch uses, since I figured from other Arch users who managed to compile but had other issues. Even through I use Gentoo myself.) it compiles fine. 

It would be nice to add the specific verison of chaiscript that Kit depends on in the Readme to clear up any issues.

Build log uploaded [here](https://bpaste.net/raw/ac5dcef9f753).

**Comment by haikarainen** [comment]
Thanks for contributing! First off, how old is your repo clone?  I have recently fixed an issue on that exact line. Can you verify that line 467 of ScriptLib.cpp looks like this:

```
{chaiscript::fun<void(kit::Application&,bool)>([](kit::Application& a, bool b) { a.getWindow()->setVSync(b); }), "setVSync"}
```

If it doesn't look like that, please fetch the latest changes (`git pull`) or do a clean `git clone`.  If it DOES look like that, please verify.

**Comment by Ristovski** [comment]
Latest commit which has to do with GLFW fails to build (see the comment I made on the commit). Will test once fixed.

**Comment by haikarainen** [comment]
I've responded to your comment. Verify your GLFW version

**Comment by Ristovski** [comment]
ScriptLib.cpp:467 is `{chaiscript::fun<void(kit::Application&,bool)>([](kit::Application& a, bool b) { a.getWindow()->setVSync(b); }), "setVSync"}`.

Can confirm issue still persists with chaiscript-5.8.1.

New build log just in case: https://bpaste.net/raw/1c03f286f584

**Comment by haikarainen** [comment]
Thanks for verifying. I will get on this.

**Comment by haikarainen** [comment]
Recreated using git branch release-5.x

**Comment by haikarainen** [comment]
Fixed via a workaround (by not using a lambda). I still really, really hope lefticus hasn't decided to remove lambda support.

**Comment by lefticus** [comment]
No, I made lambda support *better* you just needed to remove the explicit cast: 

```
{chaiscript::fun<void(kit::Application&,bool)>([](kit::Application& a, bool b) { a.getWindow()->setVSync(b); }), "setVSync"}
```

Becomes

```
{chaiscript::fun([](kit::Application& a, bool b) { a.getWindow()->setVSync(b); }), "setVSync"}
```

**Comment by haikarainen** [comment]
Thank you!
