### ISSUE TITLE
Wrong version of GLFW on Visual Studio solution

### ISSUE THREAD

**Issue by vincegogh** [haikarainen/kit#14]
Currently it is set to 3.1.2, but 3.2.0 is required. https://github.com/haikarainen/kit/blob/master/vs2015/Kit/packages.config#L4

**Comment by haikarainen** [comment]
Thank you for contributing!

**Comment by vincegogh** [comment]
Looks like there are still some remnants of 3.1.2 in the .vcxproj file. https://github.com/haikarainen/kit/blob/master/vs2015/Kit/Kit.vcxproj#L250

I don't have enough experience to fix all this stuff, why can't things just build without errors :( And yes, the empty projects seem to have gone which is good (one step closer to compiling this thing)

**Comment by haikarainen** [comment]
You still haven't made it compile? Open NuGet package manager inside visual studio, remove all dependencies, then manually re-add them. It should build fine if you do (and have chaiscript and assimp)

**Comment by vincegogh** [comment]
Ok, that seemed to almost work. But now when I run e.g the world editor, it builds ok but when I run it I get the message "Unable to start program. C:\...\kit\vs2015\Kit\x64\Debug\Kit.dll is not a valid Win32 application." I guess this means that I'm using the 32 bit version of something that I shouldn't, but I've installed Chaiscript 64 bit and I am running the Debug/x64 build configuration for the world editor, so I'm not sure what.
