### ISSUE TITLE
Cleanup needed

### ISSUE THREAD

**Issue by haikarainen** [haikarainen/kit#2]
Problems:
1. Lot of messy code
2. Lots of false information in both readme, comments and the promopage
3. Lot of stuff is missing, and some stuff seems to exist for no reason at all. Other stuff needs dire improvement.

**Comment by warmwaffles** [comment]
May want to also look at `clang-format` to make a universal format and require all PRs to abide by it.

**Comment by haikarainen** [comment]
Hey thanks for the feedback! I will definitely check this out, I think it could help alot. :+1:

**Comment by haikarainen** [comment]
This is done since long, however it is in a hidden repo as Kit is now more of a commercial product, and also a full-fledged engine.
