### ISSUE TITLE
Issues opening Font files

### ISSUE THREAD

**Issue by clayjohn** [haikarainen/kit#22]
Please bear with me if this is a dumb mistake I just spent all day figuring out vc (I usually use MinGW with make) so I may have made a mistake somewhere along the compilation process. 

Anyway the issue I'm running into is that upon running either the Material Editor or the World Editor exe's I run into a crash due to not being able to load the font file. The error returned is "Failed to load font from file" and it comes from font.cpp at line 185. Also right before the error is reported theres a message: "FT_Stream_Open: could not open './data/fonts/Inconsolata.otf' "

I'm not sure what could be causing the issue, because everything seemed like it compiled correctly and I think I have all the dependencies set up correctly.

**Comment by haikarainen** [comment]
This is like the fourth time I'm getting this. You have to run the tools from the dist directory. The error message should be a good indicator of what is wrong.
