### ISSUE TITLE
Gitter chat for Kit

### ISSUE THREAD

**Issue by HeadClot** [haikarainen/kit#27]
Would it be possible to get a Gitter for kit?

gitter.im

https://en.wikipedia.org/wiki/Gitter

I personally want to get a conversation going about this awesome engine :)

**Comment by haikarainen** [comment]
How does this differ from say Discord? I get that it's literally made for github projects, but I'm having a hard time finding any unique features.

And thank you! :)

**Comment by HeadClot** [comment]
Hey,
If you want to put up a discord go ahead - I just want to get a conversation going about Kit Engine.

**Comment by haikarainen** [comment]
Created a gitter, no idea how this works though lol. Please notify me if I've done something completely crazy. https://gitter.im/orgs/kitframework/rooms
