### ISSUE TITLE
Compiling does not create necessary folders

### ISSUE THREAD

**Issue by kylenoteboom** [haikarainen/kit#3]
I get errors like this upon running `make -j 10 && sudo make install`:
`Fatal error: can't create build/src/Kit/imgui/imgui_draw.o: No such file or directory`

The `build` directory is not made at all. If I make it myself, it seems to work.
So I made a `build` directory, then `src` inside and inside that `Kit`, and some more to make it look like this:
* kit
 * build
   * src
     * Kit
        * GL
        * imgui
        * stb
 * lib

Now the repository root's `makefile` seems to work fine, however, building any of the tools requires the same folders, as well as a `bin` folder in the same directory as the `makefile`.

Using `sudo` for the first `make` doesn't make a difference, I don't think it's a permissions issue.

**Comment by haikarainen** [comment]
Ah yes, thank you for opening this issue, had totally forgot about that. The issue is in the makefile. I tell it to write files to certain directories without creating them, easy as that.

**Comment by haikarainen** [comment]
Thanks for contributing! :+1:

**Comment by vincegogh** [comment]
I believe that the tools (importer, world editor and material designer) makefiles also do not create the `bin` folder when run.

**Comment by haikarainen** [comment]
You are probably right. I will get on this. Thank you.

**Comment by haikarainen** [comment]
@vincegogh  Please verify

**Comment by vincegogh** [comment]
@haikarainen Looks ok, trying to test it but now my chaiscript is giving me loads of random errors when I build anything. I believe it is due to this commit (0bcd7be4d9e005326c5d25bbd4d23463ea4abd82). Here's the only message I see from the kit code (Lubuntu, chaiscript 5.8.1):
 
    src/Kit/ScriptLib.cpp:467:119: note: cannot convert ‘<lambda closure object>kit::getScriptLibrary()::<lambda(kit::Application&, bool)>{}’ (type ‘kit::getScriptLibrary()::<lambda(kit::Application&, bool)>’) to type ‘void (&&)(kit::Application&, bool)’

    src/Kit/ScriptLib.cpp:469:5: error: no matching function for call to ‘add_class(chaiscript::Module&, const char [12], <brace-enclosed initializer list>, <brace-enclosed initializer list>)’

I can make a new issue if you want, but it might be an easy fix.

**Comment by haikarainen** [comment]
Are you doing this on a fresh repo clone? Do a git pull & make clean, or a fresh clone.  Verify, if the problem persists, open a new issue.
