### ISSUE TITLE
Implement support for geometry, compute & tesselation shaders

### ISSUE THREAD

**Issue by vincegogh** [haikarainen/kit#30]
Both shader classes contain the exact same code except for a few lines. Maybe it would be a good idea to split it up into a parent class? That way, it would make it easy for a GeometryShader class to be implemented  (plus, it would make storing shaders easier because you don't need two separate vectors/arrays, which could make things a little easier for the end user). 

Obviously, this isn't a priority or anything but since you are going down the route of 'cleaning up' anyway, this would make things an extra bit neater, and prevent some copy-and-pasting in the future. What do you think?

**Comment by haikarainen** [comment]
I saw your comment on IRC (and responded to it, although too late), but the reason it is like this, is because there are some things that are unique to different shader types. So back when I first implemented shaders (like 1½ years ago) I did it like this as a "temporary" thing to Fix Later (tm).

Something should be done to it before the final release though, so I'll keep this open. Thanks!

**Comment by haikarainen** [comment]
Oh right, btw

> plus, it would make storing shaders easier because you don't need two separate vectors/arrays, which could make things a little easier for the end user

I assume you're talking about passing vectors to the program constructor (as a shortcut to compiling shaders and linking the program).  This wouldnt change at all since that function needs to know what sources  should be compiled as what typ eof shader.

**Comment by vincegogh** [comment]
The things passed into `kit::Program::load` are the file paths, not the actual shader objects anyway. But I just meant more generally, if someone wanted to store shader objects in a vector then they could do it with one vector. Compute/tesselation shaders should be nice. Keep up the good work ;)

**Comment by haikarainen** [comment]
Santa came early with some huge changes. Hopefully nothing is broken for anyone right now, but this had to be done sooner rather than later.

**Comment by haikarainen** [comment]
* Both geometry shaders and tesselation shaders needs further testing. 
* Compute shaders need implementation.

**Comment by haikarainen** [comment]
There, geometry, tessellation & compute shaders should have some sort of support in Kit now. It needs further testing and feedback though, so I'll leave this open for now!
