### ISSUE TITLE
Official windows support will end

### ISSUE THREAD

**Issue by haikarainen** [haikarainen/kit#34]
As title states. I have very little time for this project, and it's in need of some dire structural changes. Maintaining a windows port is a lot of work, and I really despise Windows as an operating system for development. It's really a hassle!

I will completely drop development on Windows, but will try to maintain cross-platform compatibility when I work on it under GNU/Linux.

**Comment by xHaVoK87** [comment]
Would prefer native development under Linux regardless. This is a smart decision and I stand by it! How is work going with KIT?

**Comment by haikarainen** [comment]
@xHaVoK87  Hey thanks! :) It's going forward slowly. I have implemented some rather big changes (no more smart pointer abuse is a big one), and have been working on water lately. Will post a new example of just that soon. 

Will not have too much time starting next week though, as I start working.

**Comment by lukesanantonio** [comment]
@haikarainen How were you thinking of implementing water? I used projected grid water in the redcrane engine and I was fairly happy with the result. It's not all that pretty but it works!

**Comment by haikarainen** [comment]
@lukesanantonio  Hey man thank you for the tip!

I initially had a pretty basic thing using 2 heightmap textures blended together, but I have removed it in preparation for something better, so right now the surface is completely flat. I'm currently working on making the renderables ready for reflection drawing and implementing reflections.

I currently render a regular quad of the surface from above with its own special shader (and configurable parameters). Then pretty much the same from below, but with a different shader. And then I render a fullscreen shader if the camera is below the surface, which adds stuff like fullscreen refraction, "fog", a vignette etc. 

Right now it looks something like this:

https://www.youtube.com/watch?v=kuZt3TU0IyE&feature=youtu.be

I think with reflections it will look much less bland. It also already looks much better if you have a bunch of stuff near the surface :)

**Comment by xHaVoK87** [comment]
@haikarainen Would love to talk to you on Discord if you could add me xHaVoK87#9481 if you still have it. I'm starting work on a project that would help people get into development with KIT. Got a few guys lined up for the job as well and would love to talk with you about work related issues we may run into that could benefit you with development of the framework!

**Comment by haikarainen** [comment]
@xhavok87 sounds interesting. Im in stockholm all week for work though, I'll contact you when I fly back!
