### ISSUE TITLE
Can't compile the examples

### ISSUE THREAD

**Issue by spacepluk** [haikarainen/kit#36]
Hi there,
I was giving this a try, and the examples don't seem to compile right now.  Can you recommend a "stable" commit to do some testing?
Thanks!

**Comment by haikarainen** [comment]
Hi! I've been working quite a lot on kit lately. so things are pretty messy. Let me fix the examples real quick for you.

**Comment by haikarainen** [comment]
Ah well, the dynamic materials example is currently broken while I figure out some resource management stuff. In the meantime, I have fixed the other examples at least. Push incoming.

**Comment by haikarainen** [comment]
This issue will be fixed when #37 is

**Comment by spacepluk** [comment]
awesome thanks! :)

**Comment by haikarainen** [comment]
This is done since long, however it is in a hidden repo as Kit is now more of a commercial product, and also a full-fledged engine.

Also, the example code is since long deprecated. Sorry for any inconvenience (hold out, release this year!)
