### ISSUE TITLE
Completely revamp resource system

### ISSUE THREAD

**Issue by haikarainen** [haikarainen/kit#38]
* Create a generic .asset file format, to contain completely custom, optimized, baked formats for different assets that Kit might need.
* Figure out resource management for loaded resources. Preferrably invisible and non-blocking to the user of the framework.

**Comment by haikarainen** [comment]
This is done since long, however it is in a hidden repo as Kit is now more of a commercial product, and also a full-fledged engine.

**Comment by codecat** [comment]
So this repository is no longer getting updated at all? The engine is closed source going forward?

**Comment by haikarainen** [comment]
@codecat During the current development phase, I've locked down the source code. My plan is to release it open source once I have a good license written, but that requires some legal advisory. 

On release, it will be open source again, although under different terms. You would also need to pay 10% of any net income from a project using the engine.

**Comment by codecat** [comment]
Thanks for the clarification.
