### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [haikarainen/kit#6]
I would like to point out that an identifier like "[`__imgui_renderDrawLists`](https://github.com/haikarainen/kit/blob/8c2cd9a8ea7627bf4dfe9f44292511e935733105/include/Kit/ImguiImpl.hpp#L50 "Update candidate: UISystem class")" [does not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by haikarainen** [comment]
I'm aware of this, but ImGui is an embedded dependency. It is beyond my control and responsibility. You can find ImGui here: https://github.com/ocornut/imgui

Thanks for contributing!

**Comment by elfring** [comment]
How do you think about to [delete a few underscores from affected identifiers](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?")?

**Comment by haikarainen** [comment]
Thanks for contributing, sorry for the instant close I misread the issue. I'm working on a fix!

**Comment by haikarainen** [comment]
Is this better?  Semi-confusing specification, but from what I can tell this should be ok.

**Comment by haikarainen** [comment]
You know what, I'll just remove the double underscores alltogether. Seems easier

**Comment by elfring** [comment]
Thanks for [your improvement of some identifiers in your own source files](https://github.com/haikarainen/kit/commit/9f51c09142e301997c5cd4ff46cc10135a11fd33 "Deletion of a some underscores").

How do you think about to [improve a few identifiers in source files from a bundled software library](https://github.com/haikarainen/kit/blob/cf8e541fdc57e0f469b918a666b7aa95686bf5c0/include/Kit/imgui/imgui.h#L1101 "Update candidate: ImDrawList structure")?

**Comment by haikarainen** [comment]
Thank you for bringing it up and contributing! :+1:

I'm all for it, but I think the correct path to fix this issue is by first fixing it in ImGui, and then pull the fixed ImGui library into Kit. Otherwise I would practically create a fork of ImGui, which would be a hassle should I ever want to update it.

There are already some compiler warnings I want to get rid of in both ImGui as well as stb.

**Comment by elfring** [comment]
Would you like to [add any comments to a corresponding bug report](https://github.com/ocornut/imgui/issues/763 "Reserved identifier violations in ImGui")?

**Comment by haikarainen** [comment]
Sorry if this is offensive to you, but can you prove that you're not just some bot? I'm having a hard time distinguishing if you just have broken english and like to express yourself in consistently weird sentences, or if you're just programmed that way.

**Comment by elfring** [comment]
It seems that I "grew up" in that way.
